# Generated by Django 4.2.11 on 2024-03-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="duration",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="visit",
            name="start",
            field=models.DateTimeField(blank=True, default=""),
        ),
    ]
