# Generated by Django 4.2.11 on 2024-03-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_visit_duration_alter_visit_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='patient',
        ),
    ]
