# Generated by Django 4.2.11 on 2024-04-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_visit_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='DoctorService',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
