# Generated by Django 4.2.11 on 2024-03-29 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0003_remove_doctor_description_remove_doctor_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Мужской', max_length=255, verbose_name='Пол')),
                ('address', models.CharField(default='Derjinka', max_length=255)),
                ('phone_number', models.CharField(default='+996709706065', max_length=55)),
                ('complaints', models.TextField(blank=True, null=True)),
                ('date_of_appointment', models.DateField(blank=True, null=True, verbose_name='Дата записи')),
                ('time_of_appointment', models.TimeField(blank=True, null=True, verbose_name='Время записи')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='doctor.doctor')),
            ],
        ),
    ]
