# Generated by Django 4.2.11 on 2024-04-04 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctor_description_remove_doctor_experience_and_more'),
        ('patient', '0003_alter_patient_recording'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_for_appointment', models.TimeField(blank=True, null=True, verbose_name='Время записи')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_appointment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='recording',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='time_of_appointment',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appointment', models.DateField(blank=True, null=True, verbose_name='Дата записи')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='doctor.doctor')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='patient.time')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='patient.book'),
            preserve_default=False,
        ),
    ]
