# Generated by Django 4.2.11 on 2024-04-04 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctor_description_remove_doctor_experience_and_more'),
        ('patient', '0004_time_remove_patient_date_of_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='book',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_appointment',
            field=models.DateField(blank=True, null=True, verbose_name='Дата записи'),
        ),
        migrations.AddField(
            model_name='patient',
            name='recording',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='time_of_appointment',
            field=models.TimeField(blank=True, null=True, verbose_name='Время записи'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
